name: SEU Auto Temperature
on:
  schedule:
    - cron: '10 23 * * *'
    # cron 表达式，时区是 UTC 时间，比我们早 8 小时，如上所表示的是每天 UTC 时间的 23 点 10 分整， 北京时间的 07 点 10 分（24 小时制）
    # 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-time/
  watch:
    types: started

jobs:
  Temperature:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        ID: ${{ secrets.ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        pip3 install -r requirements.txt
        python3 auto_temperature.py
